name: Node.js CI

# Chạy workflow khi push hoặc pull request vào nhánh main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  # Tên job là 'build' (hoặc bạn có thể đặt tên khác)
  build:
    # Chạy trên máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Node.js
      # Thay '18.x' bằng phiên bản Node.js phù hợp với dự án của bạn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' 
          cache: 'npm' # Bật cache cho npm để tăng tốc cài đặt

      # Bước 3: Cài đặt dependencies
      # npm ci nhanh và ổn định hơn trong CI, yêu cầu package-lock.json
      # Nếu không có package-lock.json, dùng 'npm install'
      - name: Install dependencies
        run: npm ci 

      # Bước 4: Chạy script Node.js
      # Do code index.js đã được sửa để tự thoát trong môi trường CI,
      # bước này sẽ hoàn thành thành công nếu server khởi động được.
      # Biến môi trường CI=true được tự động cung cấp bởi GitHub Actions runner.
      - name: Run application script
        run: node index.js

      # (Tùy chọn) Thêm các bước khác nếu cần, ví dụ:
      # - name: Run linters
      #   run: npm run lint
      # - name: Run tests
      #   run: npm test 
